spring:
  application:
    name: education

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##education
    password: java1234

  thymeleaf:
    cache: false

#JPA 설정
  jpa:
    database: oracle
    generate-ddl: false
    hibernate:
      ddl-auto: none #create: 기존꺼를 삭제하고 다시 생성한다., update > 테이블이 없으면 새로 생성하고 있으면 업데이트해서 유지한다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    show-sql: true #자동 생성된 SQL을 로그에 출력
    properties:
     hibernate:
       format_sql: true #SQL을 이쁘게

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google  
            client-id: #본인 구글 API아이디
            client-secret: #본인 구글 API키
            redirect-uri: http://localhost:8090/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

server:
  port: 8090    

